### ISSUE TITLE
Unpaired reads?

### ISSUE THREAD

**Issue by mikheyev** [lucian-ilie/SAGE2#2]
Dear Lucian,

I would like to assemble a dataset consisting of long overlapping Illumina reads that I have separately merged into single-end super-reads. It is not clear from the documentation, does SAGE2 accept single-end reads as input?

Thanks,

Sasha

**Comment by mmolnar2** [comment]
Hi Sasha,

No, SAGE2 was implemented to only use paired-end reads.

Sorry,

Mike
